---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: gitops-core
  namespace: openshift-gitops
spec:
  repo:
    initContainers:
      - name: policy-generator-install
        image: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v2.15
