---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: pg-acs
policyDefaults:
  namespace: policies
  remediationAction: enforce
  consolidateManifests: false
  evaluationInterval:
    compliant: 30s
    noncompliant: 10s
  policySets:
    - acs-operator-hub
placementBindingDefaults:
  name: acs-operator-binding
policies:
  - name: acs-operator
    remediationAction: enforce
    policySets:
      - acs-operator-hub
      - acs-operator-managed
    manifests:
      - path: operator/

  - name: acs-operator-status
    remediationAction: InformOnly
    policySets:
      - acs-operator-hub
      - acs-operator-managed
    manifests:
      - path: health/operator/operator-status.yaml
        remediationAction: InformOnly
        extraDependencies:
          - name: acs-operator
            kind: ConfigurationPolicy

  - name: acs-central
    remediationAction: enforce
    policySets:
      - acs-operator-hub
    dependencies:
      - name: acs-operator
        compliance: Compliant
    manifests:
      - path: central/central.yaml
      - path: central/consolelink.yaml
      - path: health/central/central-status.yaml
        remediationAction: InformOnly
        extraDependencies:
          - name: acs-central
            kind: ConfigurationPolicy
            compliance: Compliant
  - name: acs-central-init-bundle
    remediationAction: enforce
    policySets:
      - acs-operator-hub
    dependencies:
      - name: acs-central
        compliance: Compliant
    manifests:
      - path: central/init-bundle/serviceaccount.yaml
      - path: central/init-bundle/role.yaml
      - path: central/init-bundle/rolebinding.yaml
      - path: central/init-bundle/job.yaml
        extraDependencies:
          - name: acs-central-init-bundle
            kind: ConfigurationPolicy
            compliance: Compliant
          - name: acs-central-init-bundle2
            kind: ConfigurationPolicy
            compliance: Compliant
          - name: acs-central-init-bundle3
            kind: ConfigurationPolicy
            compliance: Compliant
  - name: acs-central-init-bundle-cert
    remediationAction: enforce
    policySets:
      - acs-operator-hub
    dependencies:
      - name: acs-central-init-bundle
        compliance: Compliant
    manifests:
      - path: health/central/init-bundle/sensor-tls-cert.yaml
        name: acs-bundle-certificates
      - path: central/init-bundle/expired-sensor-tls.yaml
        remediationAction: InformOnly
        name: expired-sensor-tls
      - path: sensor/securedcluster.yaml
        extraDependencies:
          - name: expired-sensor-tls
            kind: ConfigurationPolicy
            compliance: Compliant
  - name: acs-central-expired-certs
    remediationAction: enforce
    complianceType: mustnothave
    policySets:
      - acs-operator-hub
    dependencies:
      - name: acs-central-init-bundle-cert
        compliance: NonCompliant
    ## ignorePending prevents the NotCompliant dependency from causing this policy to always report as pending
    ignorePending: true
    manifests:
      - path: central/init-bundle/expired-admission-control-tls.yaml
      - path: central/init-bundle/expired-collector-tls.yaml
      - path: central/init-bundle/expired-sensor-tls.yaml
      - path: central/init-bundle/job.yaml
        extraDependencies:
          - name: acs-central-expired-certs
            kind: ConfigurationPolicy
            compliance: Compliant
          - name: acs-central-expired-certs2
            kind: ConfigurationPolicy
            compliance: Compliant
          - name: acs-central-expired-certs3
            kind: ConfigurationPolicy
            compliance: Compliant
  - name: acs-sensor-sync-certs
    remediationAction: enforce
    policySets:
      - acs-operator-hub
    dependencies:
      - name: acs-central-init-bundle-cert
        compliance: Compliant
    manifests:
      - path: sensor/sensor-sync-tls-certs.yaml
  - name: acs-sensor
    remediationAction: enforce
    policySets:
      - acs-operator-managed
    manifests:
      - path: sensor/propagate-admission-control-tls.yaml
      - path: sensor/propagate-collector-tls.yaml
      - path: sensor/propagate-sensor-tls.yaml
      - path: sensor/securedcluster.yaml
        extraDependencies:
          - name: acs-sensor
            kind: ConfigurationPolicy
            compliance: Compliant
          - name: acs-sensor2
            kind: ConfigurationPolicy
            compliance: Compliant
          - name: acs-sensor3
            kind: ConfigurationPolicy
            compliance: Compliant
policySets:
  - name: acs-operator-hub
    placement:
      placementName: hub-clusters
  - name: acs-operator-managed
    placement:
      placementName: workload-clusters
