---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: pg-openshift-virtualization
policyDefaults:
  namespace: policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - openshift-virtualization
placementBindingDefaults:
  name: virtualization-operator-binding

policies:
  - name: openshift-virt-operator
    description: Ensure deployment of the openshift-virtualization operator.
    remediationAction: enforce
    manifests:
      - path: operator/

  - name: openshift-virt-operator-status
    description: Non-compliance indicates an operator upgrade is available.
    remediationAction: InformOnly
    manifests:
      - path: health/
    dependencies:
      - name: openshift-virt-operator
        compliance: Compliant

  - name: openshift-virt-operator-config
    description: Ensure configuration of the openshift-virtualization operator.
    remediationAction: enforce
    manifests:
      - path: instance/
    dependencies:
      - name: openshift-virt-operator
        compliance: Compliant

policySets:
  - name: openshift-virtualization
    placement:
      placementName: virtualization-host-clusters
