apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: Manual
  name: openshift-pipelines-operator-rh
  source: cs-redhat-operator-index-v4-18
  sourceNamespace: openshift-marketplace
