---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: metallb-policies
policyDefaults:
  namespace: policies
  remediationAction: enforce
placementBindingDefaults:
  name: metallb-operator-binding

policies:
  - name: metallb-operator
    manifests:
      - path: operator/

  - name: metallb-operator-status
    remediationAction: InformOnly
    manifests:
      - path: health/
    dependencies:
      - name: metallb-operator
        compliance: Compliant

  - name: metallb-operator-configuration
    remediationAction: enforce
    manifests:
      - path: instance/
    dependencies:
      - name: metallb-operator
        compliance: Compliant

policySets:
  - name: metallb-operator-policyset
    placement:
      placementName: openshift-clusters
