# Not automatically applied due to secret content.
# These need to be manually applied and not stored in the repo.
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-cluster-gitops
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/aushacker/ocp-bootstrap.git
  username: USERID
  password: TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-policies
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/aushacker/ocp-bootstrap.git
  username: USERID
  password: TOKEN
