---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: acm-operator-install
spec:
  complianceType: musthave
  complianceConfig:
    catalogSourceUnhealthy: NonCompliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  remediationAction: enforce
  removalBehaviour:
    clusterServiceVersions: Delete
    customResourceDefinitions: Delete
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: high
  upgradeApproval: Manual
  subscription:
    channel: release-2.14
    name: advanced-cluster-management
    namespace: open-cluster-management
    source: cs-redhat-operator-index-v4-18
    sourceNamespace: openshift-marketplace
  operatorGroup:
    name: open-cluster-management
    targetNamespaces:
      - open-cluster-management
