---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: pg-acm
policyDefaults:
  namespace: policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - acm-operator
placementBindingDefaults:
  name: acm-operator-binding

policies:
  - name: acm-operator
    description: Ensure deployment of the ACM operator to hub clusters.
    remediationAction: enforce
    manifests:
      - path: operator/namespace.yaml
      - path: operator/operatorgroup.yaml
      - path: operator/subscription.yaml

  - name: acm-operator-status
    description: Non-compliance indicates an operator upgrade is available.
    remediationAction: InformOnly
    manifests:
      - path: health/operator-status.yaml
    dependencies:
      - name: acm-operator
        compliance: Compliant

  - name: acm-operator-configuration
    description: Ensure configuration of the ACM operator.
    remediationAction: enforce
    manifests:
      - path: instance/multiclusterhub.yaml
    dependencies:
      - name: acm-operator
        compliance: Compliant

policySets:
  - name: acm-operator
    placement:
      placementName: hub-clusters
